### ISSUE TITLE
Student review quiz does not show unanswered questions

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#402]
This was raised in #261 - it's still the case that if I don't give an answer for one of the questions in a quiz, that question won't appear when I review the quiz later. All questions should be visible.

**Comment by sohilpandya** [comment]
Linked to #316

**Comment by stianr** [comment]
Now seems to be working - safe to close issue?

**Comment by stianr** [comment]
Not working in current version, so leaving open for future work.

**Comment by iteles** [comment]
@stianr How strange as this is one of the last things we fixed in #316!

**Comment by stianr** [comment]
@iteles yes, it seemed to be working before, but I played along in the lecture last week, and only answered one question - now reviewing the quiz I can only see that one question. Will investigate when it occurs more thoroughly.

**Comment by iteles** [comment]
Thanks @stianr

**Comment by sohilpandya** [comment]
@stianr Also just tested this locally and it looks to be working ok as seen in the screenshot below. 
![screen shot 2017-03-30 at 18 30 31](https://cloud.githubusercontent.com/assets/2305591/24517691/0e4c76aa-1577-11e7-9c1a-2398cc27d42a.png)

**Comment by stianr** [comment]
Have tested it myself too, and it seems to be working - unanswered questions from the quiz in Feb still missing, so presumably something has been update since then.
